{"name": "test_negative_login", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\n  - navigating to \"https://app.clickup.com/login\", waiting until \"load\"", "trace": "browser = <Browser type=<BrowserType name=chromium executable_path=C:\\Users\\apacha1\\AppData\\Local\\ms-playwright\\chromium-1161\\chrome-win\\chrome.exe> version=134.0.6998.35>\n\n    @allure.feature('Test negative UI login expecting error to appear')\n    def test_negative_login(browser):\n        username = 'cornybestgags@gmail.com'\n        password = '123qwe'\n        page = browser.new_page()\n        login_page = LoginPage(page)\n>       login_page.login(username, password)\n\ntests\\ui\\test_login_page.py:19: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \npages\\login_page.py:17: in login\n    self.navigate_and_wait_url(self._get_page_url)\npages\\base_page.py:23: in navigate_and_wait_url\n    self.page.goto(url)\nvenv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py:9020: in goto\n    self._sync(\nvenv\\Lib\\site-packages\\playwright\\_impl\\_page.py:552: in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\nvenv\\Lib\\site-packages\\playwright\\_impl\\_frame.py:145: in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\nvenv\\Lib\\site-packages\\playwright\\_impl\\_connection.py:61: in send\n    return await self._connection.wrap_api_call(\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\nself = <playwright._impl._connection.Connection object at 0x0000020EC8CBF4D0>, cb = <function Channel.send.<locals>.<lambda> at 0x0000020EC9030540>\nis_internal = False\n\n    async def wrap_api_call(\n        self, cb: Callable[[], Any], is_internal: bool = False\n    ) -> Any:\n        if self._api_zone.get():\n            return await cb()\n        task = asyncio.current_task(self._loop)\n        st: List[inspect.FrameInfo] = getattr(task, \"__pw_stack__\", inspect.stack())\n        parsed_st = _extract_stack_trace_information_from_stack(st, is_internal)\n        self._api_zone.set(parsed_st)\n        try:\n            return await cb()\n        except Exception as error:\n>           raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\nE           playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nE           Call log:\nE             - navigating to \"https://app.clickup.com/login\", waiting until \"load\"\n\nvenv\\Lib\\site-packages\\playwright\\_impl\\_connection.py:528: TimeoutError"}, "steps": [{"name": "Load URL - {url}", "status": "broken", "statusDetails": {"message": "playwright._impl._errors.TimeoutError: Page.goto: Timeout 30000ms exceeded.\nCall log:\n  - navigating to \"https://app.clickup.com/login\", waiting until \"load\"\n\n", "trace": "  File \"C:\\Apps\\clickup_tests\\pages\\base_page.py\", line 23, in navigate_and_wait_url\n    self.page.goto(url)\n    ~~~~~~~~~~~~~~^^^^^\n  File \"C:\\Apps\\clickup_tests\\venv\\Lib\\site-packages\\playwright\\sync_api\\_generated.py\", line 9020, in goto\n    self._sync(\n    ~~~~~~~~~~^\n        self._impl_obj.goto(\n        ^^^^^^^^^^^^^^^^^^^^\n            url=url, timeout=timeout, waitUntil=wait_until, referer=referer\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        )\n        ^\n    )\n    ^\n  File \"C:\\Apps\\clickup_tests\\venv\\Lib\\site-packages\\playwright\\_impl\\_sync_base.py\", line 115, in _sync\n    return task.result()\n           ~~~~~~~~~~~^^\n  File \"C:\\Apps\\clickup_tests\\venv\\Lib\\site-packages\\playwright\\_impl\\_page.py\", line 552, in goto\n    return await self._main_frame.goto(**locals_to_params(locals()))\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Apps\\clickup_tests\\venv\\Lib\\site-packages\\playwright\\_impl\\_frame.py\", line 145, in goto\n    await self._channel.send(\"goto\", locals_to_params(locals()))\n  File \"C:\\Apps\\clickup_tests\\venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 61, in send\n    return await self._connection.wrap_api_call(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<2 lines>...\n    )\n    ^\n  File \"C:\\Apps\\clickup_tests\\venv\\Lib\\site-packages\\playwright\\_impl\\_connection.py\", line 528, in wrap_api_call\n    raise rewrite_error(error, f\"{parsed_st['apiName']}: {error}\") from None\n"}, "start": 1745053824774, "stop": 1745053855809}], "start": 1745053824491, "stop": 1745053855813, "uuid": "6e849da1-baad-4356-a821-e190fbc188be", "historyId": "e87bd65a3cb2ec7fe3812cad558724e0", "testCaseId": "e87bd65a3cb2ec7fe3812cad558724e0", "fullName": "tests.ui.test_login_page#test_negative_login", "labels": [{"name": "feature", "value": "Test negative UI login expecting error to appear"}, {"name": "parentSuite", "value": "tests.ui"}, {"name": "suite", "value": "test_login_page"}, {"name": "host", "value": "apachai"}, {"name": "thread", "value": "23104-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.ui.test_login_page"}]}